---
# tasks file for microsoft_office
- name: Get uptime
  command: uptime
  register: uptime_output
  
- name: Print uptime
  debug:
    msg: "Uptime is {{ uptime_output.stdout }}"

- name: Get last logins
  command: last
  register: the_last_of_us

- name: Print the last of us
  debug:
    msg: "Here is hte last of us {{ the_last_of_us }}"